import os
import subprocess
import shutil
from django.conf import settings
from django.core.files import File
from pathlib import Path

def generate_video_thumbnail(video_instance):
    """
    Generates a thumbnail for a video instance using ffmpeg.
    """
    if not video_instance.file:
        return

    # Check if ffmpeg is installed
    if not shutil.which('ffmpeg'):
        print("Warning: FFmpeg not found. Video thumbnail will not be generated.")
        return

    video_path = video_instance.file.path
    thumbnail_name = f"{video_instance.id}_thumbnail.jpg"
    thumbnail_path = os.path.join(os.path.dirname(video_path), thumbnail_name)

    # Ensure directory exists
    os.makedirs(os.path.dirname(thumbnail_path), exist_ok=True)

    # FFmpeg command to extract a frame at 1 second
    command = [
        'ffmpeg',
        '-i', video_path,
        '-ss', '00:00:01.000',
        '-vframes', '1',
        '-y',
        thumbnail_path
    ]

    try:
        subprocess.check_call(command)
        
        # Save the thumbnail to the model
        with open(thumbnail_path, 'rb') as f:
            video_instance.cover.save(thumbnail_name, File(f), save=True)
            
        # Remove the temp file generated by ffmpeg after saving to model
        if os.path.exists(thumbnail_path):
             os.remove(thumbnail_path)
             
    except subprocess.CalledProcessError as e:
        print(f"Error generating thumbnail: {e}")
    except Exception as e:
        print(f"An error occurred during thumbnail generation: {e}")
